server:
  port: 8081
  servlet:
    context-path: /rabbitmq-demo/

#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.15.104:3306/test
    username: root
    password: root

  rabbitmq:
    host: 192.168.15.104
    port: 5672
    username: root
    password: root
    # 消费者相关配置
    listener:
      simple:
        # 每个消费者线程预先拉取的数量
        # prefetch: 4
        # 最小消费者数量
        concurrency: 2
        # 最大消费者数量
        #        max-concurrency: 10
        # 手动确认
        acknowledge-mode: manual
        # 开启重试
        retry:
          enabled: true
          # 最大重试次数
          max-attempts: 2
          # 每隔5s重试一次
          maxInterval: 2000